var a = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lobortis arcu vitae dui varius aliquet. Aliquam aliquam, erat ut rutrum imperdiet, augue elit auctor metus, eu fermentum ligula metus sed velit. Quisque feugiat dolor ut sodales sagittis. Phasellus sagittis, nisi nec egestas venenatis, est risus viverra urna, ac euismod risus est a velit. Quisque id est dignissim tortor fermentum vestibulum vel eget eros. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis quis neque id ligula suscipit euismod. Duis metus dui, facilisis eu congue non, commodo ut ligula. Ut felis lorem, adipiscing at luctus vel, sagittis nec ante. Cras vitae odio vitae nisl commodo auctor non a nibh. Pellentesque porta nulla tristique, faucibus nibh non, tincidunt tellus. Phasellus vitae tortor at dolor vestibulum laoreet vitae condimentum turpis. Donec pellentesque est sed ante lacinia, ut laoreet purus congue.";

var b = "Aenean fermentum condimentum dolor ac euismod. Phasellus fermentum libero mi, a condimentum purus hendrerit consequat. Donec tincidunt magna odio, vitae aliquam urna aliquam cursus. Nullam venenatis lacinia hendrerit. Mauris blandit arcu at velit eleifend porttitor. Maecenas eget volutpat velit, non elementum sem. In vestibulum sem velit, et pulvinar augue luctus vitae. Ut pretium ipsum nec odio eleifend interdum in ut tortor. Aliquam pellentesque quis est vel semper. Praesent ac ante lacinia, pellentesque nulla semper, lobortis velit. Pellentesque id mauris quis diam rhoncus suscipit.";

var c = "Phasellus mattis arcu eget nisi egestas, quis auctor mauris ultrices. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vel ornare ligula, vitae vulputate elit. Praesent in sem nec nibh iaculis vestibulum. Duis non elit sit amet nibh venenatis condimentum vel quis justo. Donec convallis iaculis libero vitae feugiat. Nunc non risus malesuada sem semper venenatis ac hendrerit ipsum. Duis quis quam venenatis, consequat nisl at, gravida lacus.";

var d = "Cras nulla massa, rutrum in tortor ut, pharetra tincidunt enim. Pellentesque placerat cursus arcu. Sed fermentum hendrerit accumsan. Quisque in accumsan urna, vulputate suscipit nunc. Mauris non nisi nec tortor fermentum interdum ac vitae ligula. Suspendisse bibendum, lorem a molestie placerat, arcu enim lobortis massa, eget luctus dolor augue eget augue. Aenean quis dapibus augue, non mattis tellus. Pellentesque dignissim ante ac faucibus mattis. Aliquam rutrum nisl et felis interdum, ac consectetur sapien sagittis. Maecenas blandit, lectus ac porttitor elementum, arcu leo mattis ante, ac iaculis justo quam in dui. Vestibulum ullamcorper aliquam eros id sollicitudin. Mauris vitae rhoncus eros, in elementum nisl. Proin sit amet nunc id urna sagittis convallis at quis dolor. Suspendisse malesuada est at purus aliquam, vitae vestibulum magna congue.";

var e = "Fusce venenatis orci quis malesuada placerat. Fusce et nisi id turpis ultricies suscipit et in leo. Sed in eros nisl. In leo nunc, fringilla id malesuada eu, hendrerit aliquet tellus. In fringilla leo at tellus vehicula, at molestie mauris sollicitudin. Pellentesque mollis nibh urna, sit amet tincidunt enim mattis et. Donec at porttitor tellus.";

var f = "Donec sit amet felis tempus, porttitor quam vel, ultricies nunc. Aenean a nisl a turpis scelerisque dapibus eu vel nulla. Maecenas tincidunt odio nulla, ut posuere metus sagittis quis. Duis molestie consectetur interdum. Aliquam sit amet diam sed leo dictum facilisis. Quisque auctor metus sapien, et venenatis nulla malesuada tempor. Aliquam at est bibendum lectus posuere placerat id et eros. Etiam blandit vehicula ligula interdum facilisis. Fusce vulputate eros sem, eu condimentum tellus consequat nec. Vivamus sit amet nisl orci. Fusce ullamcorper lacus condimentum mauris porttitor, ut porta neque faucibus.";

var g = "Etiam ultricies faucibus dui in pharetra. Etiam purus nisi, consequat aliquet sollicitudin vel, dictum non ante. Ut tempor eget mauris eu volutpat. Quisque vel posuere arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla facilisi. Proin lectus velit, fringilla eget sapien et, commodo eleifend urna. Etiam faucibus et lacus quis volutpat. Aliquam vestibulum purus vitae augue aliquet sagittis. Integer quis nunc vestibulum sem vehicula lobortis. Nulla at ante lacus. Vestibulum in dui diam. Aliquam tristique magna et justo bibendum mattis. Phasellus in tincidunt enim. Curabitur nibh lorem, vulputate ut nibh vitae, congue interdum elit.";

var h = "Nulla auctor sodales molestie. Vivamus nec lacus a lacus laoreet ultrices ut a neque. Mauris interdum elit ac eros aliquam, vel elementum justo commodo. Vivamus dapibus ligula in ante fringilla porta. Ut aliquam dui urna, nec dictum nulla rutrum a. Donec lacinia ultrices nisi sed semper. Morbi a eleifend dolor.";

var i = "Vivamus in vehicula orci. Nunc et neque vel enim tincidunt placerat non vitae leo. Nulla luctus, urna at tincidunt congue, est nisi rutrum dui, eu gravida lacus quam vel nunc. Nunc vitae justo tempus risus ornare ultrices nec quis mi. Aliquam eget risus facilisis, tristique leo mollis, tincidunt lacus. Fusce sed nibh fermentum, ornare libero a, sagittis ligula. In hac habitasse platea dictumst. Aenean ut lorem in sem dapibus tincidunt. Nam non ullamcorper est, non feugiat sapien. Curabitur malesuada enim quis pulvinar ullamcorper. Donec pellentesque nisi ipsum. Cras eu sem ac erat faucibus laoreet. Nulla facilisi. Nam vel libero in nibh consequat rutrum at nec mauris. Etiam pretium tempor mi, in hendrerit diam ullamcorper commodo. Phasellus lacus sapien, tincidunt a dui vel, imperdiet aliquam mi.";

var j = "Suspendisse dapibus blandit elit et pellentesque. Cras bibendum, libero a egestas porta, urna neque dignissim dui, id pellentesque mi enim in lacus. Cras fermentum justo odio, sed gravida tortor suscipit ac. Donec dignissim vehicula est eget feugiat. Vivamus vitae mollis nisl. Aliquam nec mollis tellus. Nulla facilisi. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris tempus dui vitae ullamcorper tempus. Suspendisse sed dolor eu ligula auctor dictum quis sit amet augue. Mauris nec erat nulla. Morbi luctus ante erat, sed tincidunt arcu semper dictum. Nullam purus metus, auctor a ornare eget, feugiat a sapien.";
